### PR TITLE
Add kafka backend for log verification

### PR DESCRIPTION
**Pull request by smalleni**
Signed-off-by: Sai Sindhur Malleni <smalleni@redhat.com>

### CODE REVIEW

**Comment by smalleni** [comment]
```2021-05-10T22:01:47Z - INFO     - MainProcess - trigger_log_generator: All messages sent
2021-05-10T22:01:47Z - INFO     - MainProcess - trigger_log_generator: Confirming all 60 messages received in backend
2021-05-10T22:01:53Z - INFO     - MainProcess - trigger_log_generator: All messages received by backend
2021-05-10T22:01:53Z - INFO     - MainProcess - trigger_log_generator: Total messages received: 60 Total messages expected: 60
2021-05-10T22:01:53Z - INFO     - MainProcess - trigger_log_generator: Seconds till backend received all messages: 5
2021-05-10T22:01:53Z - INFO     - MainProcess - trigger_log_generator: Finished executing logging test
2021-05-10T22:01:53Z - INFO     - MainProcess - run_snafu: Duration of execution - 0:01:06, with total size of 240 bytes
```

**Comment by smalleni** [comment]
@dry923 Good to review now

**Review by dry923 — APPROVED** [review]
LGTM!

**Comment by smalleni** [comment]
> LGTM!

Thanks for looking, can we get this merged please?

**Review by whitleykeith — APPROVED** [review]
lgtm

**Pull request merged**
