### PR TITLE
Add additional try in case the env is openstack

### PR DESCRIPTION
**Pull request by dry923**
Openstack is labeled different for its environment. So i added an additional try with the platform to add openstack as a fallback. Worst case it gets labeled with "Unknown"

### CODE REVIEW

**Comment by dry923** [comment]
Failing on: 
```
14:30:26 ++ kubectl apply -f tests/test_crs/valid_scale_up.yaml
14:30:26 The Benchmark "scale" is invalid: spec.elasticsearch.port: Invalid value: "null": spec.elasticsearch.port in body must be of type integer: "null"
```

Which has nothing to do with my changes.

**Comment by dry923** [comment]
> Failing on:
> 
> ```
> 14:30:26 ++ kubectl apply -f tests/test_crs/valid_scale_up.yaml
> 14:30:26 The Benchmark "scale" is invalid: spec.elasticsearch.port: Invalid value: "null": spec.elasticsearch.port in body must be of type integer: "null"
> ```
> 
> Which has nothing to do with my changes.

@rsevilla87 did you modify something with the port information for the snafu tests?

**Review by masco — APPROVED** [review]
LGTM

**Review by chaitanyaenr — APPROVED** [review]
LGTM

**Review by mohit-sheth — APPROVED** [review]
LGTM

**Pull request merged**
