### PR TITLE
Fs drift cleanups

### PR DESCRIPTION
**Pull request by bengland2**
these changes allowed me to run fs-drift for an hour and a half and get data even in the presence of intervals where some threads were hung due to MDS crashes.

### CODE REVIEW

**Comment by aakarshg** [comment]
@bengland2 seems to be failing linters, following are the errors:
```
./fs_drift_wrapper/trigger_fs_drift.py:69:33: E201 whitespace after '['
            fsd_output_lines = [ l.strip().decode('utf-8') for l in fsd_output.splitlines() ]
                                ^
./fs_drift_wrapper/trigger_fs_drift.py:69:92: E202 whitespace before ']'
            fsd_output_lines = [ l.strip().decode('utf-8') for l in fsd_output.splitlines() ]
                                                                                           ^
./fs_drift_wrapper/trigger_fs_drift.py:70:38: E701 multiple statements on one line (colon)
            for l in fsd_output_lines: print(l)
                                     ^
./fs_drift_wrapper/trigger_fs_drift.py:95:9: F841 local variable 'elapsed_time' is assigned to but never used
        elapsed_time = float(data['results']['elapsed'])
        ^
./fs_drift_wrapper/trigger_fs_drift.py:173:37: E711 comparison to None should be 'if cond is None:'
                        if rate_obj == None:
```

Can you please fix it so linter lords are happy

**Comment by bengland2** [comment]
sure I'll fix, didn't know it was complaining.

**Comment by bengland2** [comment]
really sorry, this one got away from me, will try to get to it once cache dropping is over (fs-drift may need cache dropping too).

**Comment by jtaleric** [comment]
hey @bengland2 should we close this out?

**Comment by bengland2** [comment]
Sorry, I just don't have time for fs-drift right now.   Will take it off the supported list since no one but me is using it AFAIK.  Cephfs is just not as high a priority at the present time, until we get coverage for S3 (Ceph RGW and Noobaa) and get RBD running fast.

**Comment by jtaleric** [comment]
ack, so i will close this for now. Thanks Ben!

**Pull request closed without merging**
