### PR TITLE
Add summary output for uperf

### PR DESCRIPTION
**Pull request by jtaleric**
### Description

Uperf spews raw per-second data to the screen. Instead, we should
provide a summary of the results.

The only issue here, is the user doesn't have the contextg of what the
test was, since it is in XML and read in via a file. This could be later
improved to read in the XML to understand the sort of test.

### CODE REVIEW

**Comment by jtaleric** [comment]
Not sure why that check is failing, as it succeeds locally?

```
(rook) jtaleric at rook-mobile in ~/dev/snafu on uperf-summary* $ black snafu/benchmarks/uperf/uperf.py
All done! ✨ 🍰 ✨
1 file left unchanged.

```

**Review by mohit-sheth — APPROVED** [review]
lgtm

**Comment by mohit-sheth** [comment]
pre-commit.ci autofix

**Comment by learnitall** [comment]
@jtaleric Snafu's black config is set in the pre-commit config, which isn't picked up by running `black` on its own. To run black with snafu's config, do a `pre-commit run black`.

**Comment by jtaleric** [comment]
Thanks @learnitall!!

**Pull request merged**
