### PR TITLE
removed / from path in order to resolve relative path to utils

### PR DESCRIPTION
**Pull request by acalhounRH**

### CODE REVIEW

**Comment by dry923** [comment]
Pre change:
```
>>> print(os.path.join(dirname, '/utils/prometheus_labels/'))
/utils/prometheus_labels/>>> print(os.path.join(dirname, '/utils/prometheus_labels/'))
/utils/prometheus_labels/
```

Post change:

```
>>> print(os.path.join(dirname, 'utils/prometheus_labels/'))
/tmp/test/snafu/snafu/utils/prometheus_labels/
```

**Review by dry923 — APPROVED** [review]
LGTM!

**Review by chaitanyaenr — APPROVED** [review]
LGTM

**Pull request merged**
