### PR TITLE
Revamp pre-commit CI 

### PR DESCRIPTION
**Pull request by learnitall**
### Description

Adds useful linting hooks to our pre-commit config and enables usage of [pre-commit's CI service](https://pre-commit.ci). Goal is to help guide our code to be more readable and maintainable by enforcing a modern, best-practice backed coding style. To accomplish this, here are the hooks that I've added or modified:

* [isort](https://pypi.org/project/isort/): Sorts imports according to PEP 8 conventions.
* [pylint](https://pylint.org/): Really great linting pair for flake8. Configuration stored at `.pylintrc`. **I've added in ignores for all existing code**, as it would take a lot of work to refactor. Goal is to comply with pylint with new code additions for the object-orientated switch.
* [pyupgrade](https://pypi.org/project/pyupgrade/): Upgrades old syntax against current best-practices.
* [mypy](http://mypy-lang.org/): Static type-checker. When type-hints are used within our code, this tool will make sure that they make sense and are consistent with the code the hints are relevant for. (For example: "you added a type hint that this function returns a list but it actually returns a string, can you fix plz?")
* Modify flake8 to check for [PEP8 naming errors](https://pypi.org/project/pep8-naming/) and [bad docstring formats](https://pypi.org/project/flake8-docstrings/)
* Modify flake8 to use config file at `.flake8`

I've been developing with these hooks for a long time and they consistently help my code just be better, I rely on them; they catch bugs, logic errors and even simple yet breaking mistakes. 

The advantage of the pre-commit CI service over our current GitHub workflow is that the pre-commit CI will run pre-commit on new PRs and commits and if any tools make changes during the run, it will create a PR with those changes. This helps keep our code consistent with our pre-commit configuration, while reducing the amount of manual work we need to do to fix our code against our hooks. Additionally, the pre-commit CI is faster and automatically updates hook versions within our configuration. More details can be found on their homepage: [https://pre-commit.ci](https://pre-commit.ci). Examples:

* Run with our current config: https://results.pre-commit.ci/run/github/373600389/1628517326.kU_MWhu4SnqWXDKaHYVApg
* Auto-update PR: https://github.com/learnitall/benchmark-wrapper/pull/2
* Auto-update run: https://results.pre-commit.ci/run/github/373600389/1627923102.yOB2B_a3T_-L6jRarGdbNQ

### Fixes

I've modified our new benchmark OOP code to be compliant with these hooks.

### CODE REVIEW

**Comment by learnitall** [comment]
Here is an example of what the pre-commit CI looks like: https://github.com/learnitall/pre-commit-ci-example

**Review by whitleykeith — APPROVED** [review]
lgtm

**Review by mohit-sheth — APPROVED** [review]
LGTM

**Comment by learnitall** [comment]
/rerun all snafu/benchmarks/uperf snafu/ycsb_wrapper snafu/scale_openshift_wrapper

**Comment by learnitall** [comment]
/rerun ec2l snafu/benchmarks/uperf snafu/scale_openshift/wrapper snafu/ycsb_wrapper

**Comment by learnitall** [comment]
Got the green light from @mohit-sheth, merging.

**Pull request merged**
