### PR TITLE
add run_id to es docs

### PR DESCRIPTION
**Pull request by whitleykeith**
Adds an optional field `run_id` to the es docs inserted by snafu

example ES doc:

```json
{
    "_index": "snafu-vegeta-results",
    "_op_type": "create",
    "_source": {
        "workload": "vegeta",
        "uuid": "test-uuid",
        "user": "snafu",
        "cluster_name": "mycluster",
        "iteration": 1,
        "duration": 30078961,
        "workers": 1,
        "keepalive": false,
        "targets": "targets.yaml",
        "hostname": "ip-172-31-43-12.us-west-2.compute.internal",
        "rps": 13,
        "throughput": 13,
        "status_codes": {
            "200": 1
        },
        "requests": 404,
        "p99_latency": 208233,
        "p95_latency": 105046,
        "max_latency": 835515,
        "min_latency": 48091,
        "req_latency": 74608,
        "timestamp": "2020-11-11 19:43:24.530419+00:00",
        "bytes_in": 48944,
        "bytes_out": 0
    },
    "_id": "f8db194dde577df56a495ecaccc049a8a2b3e998225bb357896cee74e43be463",
    "run_id": "test-me"
}
```

### CODE REVIEW

**Review by jtaleric — APPROVED** [review]
LGTM do you have an example?

**Comment by whitleykeith** [comment]
> LGTM do you have an example?

i do now :)

**Review by rsevilla87 — APPROVED** [review]
LGTM!

**Comment by jtaleric** [comment]
Waiting for CI... tick-tock.

**Review by chaitanyaenr — APPROVED** [review]
LGTM

**Pull request merged**
