### PR TITLE
put delay after cache dropping to let system recover from it

### PR DESCRIPTION
**Pull request by bengland2**
Depends-On: 378
before starting workload by caching directories, shared libraries, etc.
make delay and webservice timeout configurable with env. vars.
do not log cache dropping messages unless user requested cache dropping
tested delay with AWS EC2 cluster 
```
2020-09-09T12:02:27Z - INFO     - MainProcess - request_cache_drop: requesting kernel to drop cache via 10.128.2.64:9222
2020-09-09T12:02:37Z - INFO     - MainProcess - trigger_fio: Executing fio --client...
```

### CODE REVIEW

**Comment by dry923** [comment]
@bengland2 its failing with this error when it calls the drop_cache function
```
11:01:16 Traceback (most recent call last):
11:01:16   File "/usr/local/bin/run_snafu", line 11, in <module>
11:01:16     load_entry_point('snafu', 'console_scripts', 'run_snafu')()
11:01:16   File "/opt/snafu/snafu/run_snafu.py", line 105, in main
11:01:16     parallel_setting)
11:01:16   File "/opt/snafu/snafu/utils/py_es_bulk.py", line 166, in streaming_bulk
11:01:16     for ok, resp_payload in streaming_bulk_generator:
11:01:16   File "/usr/local/lib/python3.6/site-packages/elasticsearch/helpers/actions.py", line 212, in streaming_bulk
11:01:16     actions, chunk_size, max_chunk_bytes, client.transport.serializer
11:01:16   File "/usr/local/lib/python3.6/site-packages/elasticsearch/helpers/actions.py", line 63, in _chunk_actions
11:01:16     for action, data in actions:
11:01:16   File "/opt/snafu/snafu/utils/py_es_bulk.py", line 114, in actions_tracking_closure
11:01:16     for cl_action in cl_actions:
11:01:16   File "/opt/snafu/snafu/run_snafu.py", line 140, in process_generator
11:01:16     drop_cache()
11:01:16   File "/opt/snafu/snafu/utils/request_cache_drop.py", line 65, in drop_cache
11:01:16     if kernel_cache_drop_pod_ips.strip() != '':
11:01:16 AttributeError: 'NoneType' object has no attribute 'strip'
```

**Comment by bengland2** [comment]
turns out that request_cache_drop.py was sleeping even when cache drop wasn't requested (wrong indent), this might have caused some of the benchmarks to timeout?

**Comment by bengland2** [comment]
the fio benchmark passed this time!  uperf and scale_openshift_wrapper failed.   I want to merge this PR before benchmark-operator PR 387.   Since this PR change should never ever execute unless benchmark-operator PR 387 is installed and drop_cache_kernel: true is set, then I think it should be merged now, but I don't have the merge button.

**Comment by rsevilla87** [comment]
The scale test failed because the ripsaw bits were not merged at that moment. Now they are in this test shouldn't fail again. I'm gonna rerun tests to ensure we don't break anything and then merge-time!

**Comment by rsevilla87** [comment]
The sysbench issue is not related with any of the changes from this PR. So approving

**Review by rsevilla87 — APPROVED** [review]
LGTM!

**Review by dry923 — APPROVED** [review]
LGTM!

**Pull request merged**
