### PR TITLE
get fs-drift to pass CI again

### PR DESCRIPTION
**Pull request by bengland2**
this is not a real fix, we need to
process response time data and
process counter data into rates over time
but at least the code is structured more reasonably now
JSON parsing is removed from this module
can be fixed later as time and interest permits

### CODE REVIEW

**Comment by bengland2** [comment]
ok this is strange error message, all 6 checks above pass but the message is "8 successful and 1 failing check"???

**Comment by bengland2** [comment]
I have pushed a real fix to fs-drift benchmark-wrapper above (as well as pushing a [fix to fs-drift benchmark itself](https://github.com/parallel-fs-utils/fs-drift/pull/48)).      investigating pre-commit.ci error during build  while testing my hand-built image (which built successfully).

**Comment by bengland2** [comment]
The error during build is nothing to do with me, it is CI system not being able to authenticate itself.  Please help.

**Comment by bengland2** [comment]
this is ready to merge, has been tested in AWS with fs-drift and OCP 4.9 .   The one CI check above that failed is nothing to do with fs-drift.  Can someone please merge this?

**Comment by bengland2** [comment]
what did I do wrong to cause CI not to pass?  Last night the image build failed with github authentication error.
Screenshot from 2022-03-15 15-27-23

**Comment by learnitall** [comment]
Issue lies with our pre-commit config, I'll push a fix here in a second.

**Comment by learnitall** [comment]
@bengland2 can you merge in the updated pre-commit config from master?

**Comment by bengland2** [comment]
@learnitall I rebased my changes and it still fails but for reasons I can do something about now, thank you!

**Comment by learnitall** [comment]
Thank you for your patience with the pre-commit issues. TIL to stay up to date on GitHub's blog to stay informed on these sorts of changes.

**Pull request merged**
