### PR TITLE
disabled ofed check 

### PR DESCRIPTION
**Pull request by mukrishn**
### Fixes
Helps to run TRex on Mellanox [ConnectX-5] VFs.

### CODE REVIEW

**Comment by mukrishn** [comment]
@jtaleric There isn't any `ci_test.sh` script for TRex yet as it requires SR-IOV supported baremetal nodes.

**Comment by jtaleric** [comment]
ack `Build failure No test results found.` makes sense :D

**Review by jtaleric — APPROVED** [review]
confirmed the change to the binary and the mlx change. LGTM

**Comment by mukrishn** [comment]
@jtaleric Yes I tested them on Intel NICs (XXV710) as well. It worked without any issues. Thanks!

**Pull request merged**
