### PR TITLE
Handle case where some values don't exist gracefully

### PR DESCRIPTION
**Pull request by smalleni**
Signed-off-by: Sai Sindhur Malleni <smalleni@redhat.com>

### CODE REVIEW

**Comment by jtaleric** [comment]
Only nit is the title, benchmark-wrapper doesn't deal in CRs... but I understand what you are saying ;)

**Comment by smalleni** [comment]
> Only nit is the title, benchmark-wrapper doesn't deal in CRs... but I understand what you are saying ;)

UGH :-)

**Comment by HughNhan** [comment]
The patch fixed the issue on my local test.

**Comment by rsevilla87** [comment]
Given the merget patch at https://github.com/cloud-bulldozer/benchmark-wrapper/pull/252 , I think we don't need this anymore

**Comment by smalleni** [comment]
> Given the merged patch at #252 , I think we don't need this anymore

Yep, I guess a new PR was opened without merging this ;) @rsevilla87 I do have some questions though, for fields where values do not exist why are we assuming it to be 0? I think that is misleading, can we just not send "" ?

**Review by mohit-sheth — APPROVED** [review]
LGTM

**Review by jtaleric — APPROVED** [review]
lgtm

**Pull request merged**
