### PR TITLE
run_id should be optional

### PR DESCRIPTION
**Pull request by jtaleric**
Making run_id optional

### CODE REVIEW

**Review by mohit-sheth — APPROVED** [review]
LGTM

**Comment by dry923** [comment]
If we're defaulting it then line 181 will always be true and the if portion can be removed.

```
    if index_args.run_id:
        logger.debug(f"Run ID is {index_args.run_id}")
        es_valid_document['run_id'] = action['run_id'] = index_args.run_id
```

**Comment by jtaleric** [comment]
> If we're defaulting it then line 181 will always be true and the if portion can be removed.
> 
> ```
>     if index_args.run_id:
>         logger.debug(f"Run ID is {index_args.run_id}")
>         es_valid_document['run_id'] = action['run_id'] = index_args.run_id
> ```
> 
> +1 here, otherwise lgtm

yeah, I default the string to NA. since we will always have the key/value pair in the ES doc.

**Review by rsevilla87 — APPROVED** [review]
LGTM!

**Pull request merged**
