### PR TITLE
add support for rosa machinepools on scale wrapper

### PR DESCRIPTION
**Pull request by morenod**
### Description

Scaling workers on ROSA cannot be done editing machinesets. It requires to use the rosa tool to modify the machinepool

### Fixes
- Add required package to setup.cfg
- Add rosa parameters for login on OCM
- Add rosa binary to container image
- Modify some loggers to show correct facility (move some INFO to ERROR or DEBUG)
- Add scale up based on machinepools when rosa cluster is detected

### CODE REVIEW

**Review by chentex — APPROVED** [review]
LGTM

**Review by rsevilla87 — APPROVED** [review]
LGTM

**Comment by rsevilla87** [comment]
@morenod rebase pls

**Pull request merged**
