### PR TITLE
updated fio analyzer to handle test when bsrange is used instead of bs

### PR DESCRIPTION
**Pull request by acalhounRH**
in order to handle non-uniform distribution test we have updated benchmark-wrapper to process data when using the fio bsrange parameter.

### CODE REVIEW

**Review by dry923 — APPROVED** [review]
LGTM!

**Comment by acalhounRH** [comment]
\rerun all

**Comment by acalhounRH** [comment]
@bengland2 please review.

**Review by jtaleric — APPROVED** [review]
LGTM

**Pull request merged**
