### PR TITLE
Standardize all images to use latest tag

### PR DESCRIPTION
**Pull request by chentex**
Depends-On: https://github.com/cloud-bulldozer/benchmark-operator/pull/713

Signed-off-by: Vicente Zepeda Mas <vzepedam@redhat.com>

### Description

To follow the guidelines in here: https://github.com/cloud-bulldozer/benchmark-operator/pull/713 we need to update it here as well for tests to run

### CODE REVIEW

**Comment by chentex** [comment]
Adding discussion from old PR: https://github.com/cloud-bulldozer/benchmark-wrapper/pull/394

https://github.com/cloud-bulldozer/benchmark-wrapper/pull/394#pullrequestreview-809994957

https://github.com/cloud-bulldozer/benchmark-wrapper/pull/394#issuecomment-972942220

**Review by sjug — APPROVED** [review]
/lgtm

**Comment by dry923** [comment]
Added Depends-On line to description

**Comment by chentex** [comment]
`smallfile` is failing because the tag is pointing to `master` on `benchmark-operator` we need to merge this and https://github.com/cloud-bulldozer/benchmark-operator/pull/713 for it to pass.

**Review by dry923 — APPROVED** [review]
LGTM!

**Pull request merged**
