### PR TITLE
Add __init__.py to log_generator_wrapper

### PR DESCRIPTION
**Pull request by sarahbx**
### Description

During VM testing, both @ebattat and I encountered `ModuleNotFoundError` for `log_generator_wrapper`

```
[  159.121770] cloud-init[805]: Traceback (most recent call last):
[  159.130445] cloud-init[805]:   File "/usr/local/bin/run_snafu", line 11, in <module>
[  159.140736] cloud-init[805]:     load_entry_point('snafu==0.0.1', 'console_scripts', 'run_snafu')()
[  159.152465] cloud-init[805]:   File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
[  159.166584] cloud-init[805]:     return get_distribution(dist).load_entry_point(group, name)
[  159.177866] cloud-init[805]:   File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
[  159.192404] cloud-init[805]:     return ep.load()
[  159.200343] cloud-init[805]:   File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
[  159.213722] cloud-init[805]:     return self.resolve()
[  159.222045] cloud-init[805]:   File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
[  159.237128] cloud-init[805]:     module = __import__(self.module_name, fromlist=['__name__'], level=0)
[  159.249307] cloud-init[805]:   File "/usr/local/lib/python3.8/site-packages/snafu/run_snafu.py", line 31, in <module>
[  159.263182] cloud-initci-info: no authorized ssh keys fingerprints found for user fedora.
[805]:     from snafu.utils.wrapper_factory import wrapper_factory
[  159.280753] cloud-init[805]:   File "/usr/local/lib/python3.8/site-packages/snafu/utils/wrapper_factory.py", line 18, in <module>
[  159.295348] cloud-init[805]:     from snafu.log_generator_wrapper.log_generator_wrapper import log_generator_wrapper
[  159.309280] cloud-init[805®]: ModuleNotFoundError: No module named 'snafu.log_generator_wrapper'```
```

### Fixes
#254 
`log_generator_wrapper` subdirectory was missing `__init__.py` file, preventing module import, adding.

### CODE REVIEW

**Comment by jtaleric** [comment]
Thanks @sarahbx I wonder if there could be a test added to avoid this situation? I am curious if it is how we test/build in containers vs VM?

**Comment by jtaleric** [comment]
@dry923 hmmm curious failure above. Seems test related not patch.

**Comment by amitsagtani97** [comment]
@jtaleric @dry923 looks like..the CI checks for the last comment and picks the test name to run for it. In this case it was ->
`17:06:14 + bash ci/run_ci.sh -t I wonder if there could be a test added to avoid this 'situation?' I am curious if it is how we test/build in containers vs 'VM?'`
and started test for first word 'I'.
Maybe, there was another comment within 3 minutes[polling time for Jenkins to GitHub] after rerun command.

**Comment by sarahbx** [comment]
We are doing `pip install {repo}`, but one way we can test for this is to run `python setup.py build` and verify all packages show up in the build directory. Without the `__init__.py`, `log_generator_wrapper` does not get put into the build dir.

**Comment by jtaleric** [comment]
@amitsagtani97 @dry923 can someone run with @sarahbx patch manually? I highly doubt it breaks anything, but I want to double check. 

@sarahbx Testing for VM/CNV is obviously a gap for our CI. Is this something we can work together on to close?

**Comment by dry923** [comment]
> @amitsagtani97 @dry923 can someone run with @sarahbx patch manually? I highly doubt it breaks anything, but I want to double check.
> 
> @sarahbx Testing for VM/CNV is obviously a gap for our CI. Is this something we can work together on to close?

It failed last time because the benchmark-operator PR for the log generator wasn't merged yet so it looked for a test that wasn't there yet. I just kicked it again. I suspect it will pass as adding __init__.py shouldn't break anything.

**Review by dry923 — APPROVED** [review]
LGTM!

**Comment by dry923** [comment]
@jtaleric Looks good and it passed fine. Can you give it the second stamp and a merge please.

**Review by amitsagtani97 — APPROVED** [review]
LGTM!

**Pull request merged**
