### PR TITLE
Add delay before checking for desired upgrade version

### LINKED ISSUE #257: [Upgrade workload] Desired version takes a couple of seconds to switch
The desired version field of the clusterversion takes 2-3 seconds to change after an upgrade has been triggered. This is leading to issues with capturing the current/desired versions, introducing a delay/sleep 10 before grabbing the desired version for comparison should fix it.

### PR DESCRIPTION
**Pull request by chaitanyaenr**
This is needed as it takes a couple of seconds for the desired version
in the clusterversion spec to get updated after an upgrade has been
triggered. This commit also enables upgrading with force and even when
there are warnings around image verification.

Fixes #257

### CODE REVIEW

**Comment by chaitanyaenr** [comment]
@jtaleric We had to use --allow-upgrade-with-warnings flag since cvo runs the upgrades only when there are no warnings and looks like the nightly images are not verified thus generating a warning which is blocking the upgrades. Using this flag can potentially override the on-going upgrade, maybe we should add in a check to track that and only upgrade when there isn't one in progress, will track the issue and create a different PR to cover that case.

**Review by jtaleric — COMMENTED** [review]
Is it possible to remove the sleep and just check for the version?

**Comment by chaitanyaenr** [comment]
@jtaleric yes, updated the PR to check for the version. PTAL.

**Review by jtaleric — APPROVED** [review]
LGTM

**Pull request merged**
